WITH SUB_HISTORY AS (
    SELECT CAR_ID
         , MONTH(START_DATE) AS MONTH
         , COUNT(*) AS RECORDS
         , SUM(COUNT(CAR_ID)) OVER (PARTITION BY CAR_ID) AS SUM_CNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY MONTH, CAR_ID
    ORDER BY MONTH, CAR_ID DESC
    )

SELECT MONTH
     , CAR_ID
     , RECORDS
FROM SUB_HISTORY
WHERE SUM_CNT >= 5