-- 09:00부터 19:59까지 각 시간대별로 입양 발생 건수 조회
-- 시간대 순으로 정렬

SELECT HOUR(DATETIME)
     , COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME, '%H:%i:%s') BETWEEN '09:00:00' AND '19:59:59'
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME)